#!/usr/bin/env sh
set -eux

BUILD_PACKAGES_DEPENDENCIES=curl

curl -SLO https://github.com/phppgadmin/phppgadmin/archive/master.zip
unzip master.zip
mv ./phppgadmin-master/* /var/www/html
#mv /var/www/html/conf/config.inc.php-dist /var/www/html/conf/config.inc.php
cp /var/runtime/configs/phppgadmin/config.inc.php /var/www/html/conf/config.inc.php
#ln -s /etc/init.d/phppgadmin /etc/rc2.d/S02phppgadmin
#ln -s /etc/init.d/phppgadmin /etc/rc3.d/S02phppgadmin
#ln -s /etc/init.d/phppgadmin /etc/rc4.d/S02phppgadmin
#ln -s /etc/init.d/phppgadmin /etc/rc5.d/S02phppgadmin
rm -rf master.zip phppgadmin-master
